Cart
ZuberDunge/bat-store pull request #8
Opened 2022-02-19 18:49 UTC by ZuberDunge

2022-02-19 19:07 UTC, saadahmadhere commented on docs/login.html
> +    <style>
you forgot to remove the internal stylesheet.

2022-02-19 19:07 UTC, saadahmadhere commented on docs/login.html
> +          alt=""
alt attribute is empty

2022-02-19 19:07 UTC, saadahmadhere commented on docs/login.html
> +            alt=""
here too.

2022-02-19 19:08 UTC, saadahmadhere commented on docs/login.html
> +          <form action="">
action is empty

2022-02-19 19:08 UTC, saadahmadhere commented on docs/login.html
> +            <!-- <div>
comment should be removed here

2022-02-19 19:09 UTC, saadahmadhere commented on style/login-signup.css
> +@media screen and (max-width: 750px) {
relative units would be more appreciated. Just a suggestion

2022-02-19 19:10 UTC, saadahmadhere requested changes
Great work! Nice and clean code and file structure. But there are still some cleanup required as mentioned in the comments.

2022-02-19 19:15 UTC, saadahmadhere requested changes
Well written code. Again, some cleanups and refactoring required as requested.

2022-02-19 19:15 UTC, saadahmadhere commented on docs/cart.html
> +
extra space should be avoided

2022-02-19 19:15 UTC, saadahmadhere commented on docs/cart.html
> +
here too

2022-02-19 19:15 UTC, saadahmadhere commented on docs/cart.html
> +        <!-- <div class="main featured-area-flex bat-flex bat-align-center flex-gap-1">
unwanted comments and space should be removed

2022-02-19 19:15 UTC, saadahmadhere commented on docs/cart.html
> +              <img
here too

2022-02-19 19:15 UTC, saadahmadhere commented on style/cart.css
> +    max-width: 1200px;
using relative units is a good practice

2022-02-20 00:56 UTC, Shivanshsharma01 reviewed
The code is clean with good use of variables. Can use relative units above 16px, try implementing both reviewer's suggestions

2022-02-20 00:56 UTC, Shivanshsharma01 commented on docs/cart.html
> +              <div class="bat-flex media-nav bat-align-center flex-gap-1">
It's good to wrap the main nav in a "header" tag

2022-02-20 00:56 UTC, Shivanshsharma01 commented on docs/signup.html
> +      .slider-box {
better to remove internal style sheet from here too

2022-02-20 00:56 UTC, Shivanshsharma01 commented on style/cart.css
> +    height: 130px;
can use rem here exact values are not required

2022-02-20 05:45 UTC, ZuberDunge commented on docs/login.html
> +    <style>
Thanks for noticing Saad, I've updated it in Login PR

2022-02-20 05:45 UTC, ZuberDunge commented on docs/login.html
> +          alt=""
Thank for noticing, Fixed.

2022-02-20 05:46 UTC, ZuberDunge commented on docs/login.html
> +            <!-- <div>
Done

2022-02-20 05:46 UTC, ZuberDunge commented on docs/cart.html
> +
Will update it

2022-02-20 05:46 UTC, ZuberDunge commented on docs/cart.html
> +        <!-- <div class="main featured-area-flex bat-flex bat-align-center flex-gap-1">
DONE

2022-02-20 05:46 UTC, ZuberDunge commented on docs/signup.html
> +      .slider-box {
yes, yes i've updated it

2022-02-20 05:47 UTC, ZuberDunge commented on style/cart.css
> +    height: 130px;
I'll fix it

2022-02-20 05:50 UTC, merged